import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdtemp, realpath, rm, writeFile, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { tagFixtures } from './tag-fixtures.mjs';
const root=await realpath(await mkdtemp('/tmp/bg-web-tags-'));
await tagFixtures(root);
const server=spawn(process.execPath,['web/server.mjs'],{env:{...process.env,PORT:'0',BG_REFERENCE_ROOTS:root+'/roots.json',BG_TAG_DATA_DIR:root+'/data'},stdio:['ignore','pipe','inherit']});
let browser;
const timeout=setTimeout(()=>{server.kill();process.exit(1);},90000);
try {
  const [data]=await once(server.stdout,'data');const url=data.toString().trim().replace('Skill Atlas: ','');
  browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));let reads=0;
  page.on('request',r=>{if(/api\/(scan|repositories\/.*\/search-snapshot|scans\/.*\/search-index)/.test(r.url()))reads++;});
  await page.goto(url);await page.locator('#repository-path').fill(root+'/mps');await page.locator('#scan-button').click();
  const count=async text=>page.waitForFunction(t=>document.querySelector('#filter-count').textContent===t,text);
  await count('121 of 121');await page.getByText('Full-manifest search ready.',{exact:true}).waitFor();
  await page.locator('#tag-panel').evaluate(el=>el.open=true);
  const checkbox=id=>page.locator(`input[data-tag="${id}"]`);
  await checkbox('task:testing').waitFor();
  assert.ok((await page.locator('#tag-coverage').textContent()).includes('120 of 121'));
  const before=reads;
  await page.locator('#next-page').click();assert.equal(await page.locator('.card').count(),21);
  await page.locator('#search').fill('testneedle');await count('90 of 121');
  await checkbox('task:testing').check();await count('12 of 121');
  await checkbox('focus:agent-evals').check();await count('3 of 121');
  assert.equal(await page.locator('#text-before-tags').textContent(),'90 text matches before tags');
  assert.equal(reads,before,'Typing/facets/pages must not rescan or reread');
  await page.locator('#search').fill('otherneedle');await count('0 of 121');
  assert.equal(await checkbox('task:testing').isDisabled(),false);assert.equal(await checkbox('task:testing').isChecked(),true);
  await page.locator('#clear-search').click();await count('3 of 121');
  assert.equal(await page.locator('#search').evaluate(el=>el===document.activeElement),true);
  await page.locator('#unclassified-only').check();await count('1 of 121');assert.equal(await checkbox('task:testing').isDisabled(),true);
  assert.equal(await checkbox('task:testing').isChecked(),true);
  await page.locator('#unclassified-only').uncheck();await count('3 of 121');
  await page.locator('#clear-tags').click();await count('121 of 121');
  await page.locator('#search').fill('testneedle');await checkbox('task:testing').check();await checkbox('task:code-quality').check();await count('90 of 121');
  await page.locator('#clear-tags').click();await count('90 of 121');assert.equal(await page.locator('#search').inputValue(),'testneedle');
  await page.locator('#clear-search').click();
  await page.locator('.skill-card').first().getByRole('button',{name:'Filter by Testing',exact:true}).click();await count('12 of 121');assert.equal(await page.locator('#detail').evaluate(el=>el.open),false);
  await page.locator('#selected-tags').getByRole('button',{name:'Remove Testing',exact:true}).click();await count('121 of 121');
  await page.locator('.card[data-manifest="skills/000/SKILL.md"]').click();
  await page.locator('#manifest-content').getByText('Body text 0.',{exact:false}).waitFor();assert.ok((await page.locator('#detail-tags').textContent()).includes('Testing'));
  await page.locator('#close-detail').click();
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#download-tagged').click()]);
  const exported=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(exported.tagging.coverage.reviewed,120);assert.equal(exported.inventory.sections[0].skills.length,121);
  await writeFile(root+'/mps/skills/000/SKILL.md','# Changed\n\nChangedbody');
  await page.locator('#refresh-search').click();await page.waitForFunction(()=>document.querySelector('#tag-coverage').textContent.includes('119 of 121'));
  await page.locator('#search-scope').selectOption('all');await count('122 of 122');
  await page.locator('#search').fill('Ownerneedle');await count('1 of 122');await page.locator('.card').click();
  await page.waitForFunction(()=>document.querySelector('#manifest-content').textContent.includes('Other repository manifest.'));
  assert.ok((await page.locator('#detail-tags').textContent()).includes('Debugging'));assert.ok((await page.locator('#detail-repository').textContent()).includes('/koog'));
  await page.locator('#close-detail').click();await page.setViewportSize({width:390,height:844});
  await page.locator('#clear-search').click();await count('122 of 122');await page.locator('#tag-panel').evaluate(el=>el.open=true);
  await checkbox('task:testing').focus();await page.keyboard.press('Space');await count('11 of 122');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'reports/web-tags-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
  console.log('Tags browser checks passed: 90→12→3, facets, counts, pagination, unknown/stale lifecycle, ownership, export and mobile keyboard.');
} finally {clearTimeout(timeout);await browser?.close();server.kill();await once(server,'exit');await rm(root,{recursive:true,force:true});}
