import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const server = spawn(process.execPath, ['web/server.mjs'], { cwd: root, env: { ...process.env, PORT: '0' }, stdio: ['ignore', 'pipe', 'inherit'] });
let browser;
const timeout = setTimeout(() => { console.error('Browser smoke test timed out'); server.kill(); process.exit(1); }, 60000);
try {
  const [chunk] = await once(server.stdout, 'data');
  const url = chunk.toString().trim().replace('Skill Atlas: ', '');
  browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH || undefined });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.locator('#repository-path').fill(path.join(root, 'tests/fixtures/corner-cases'));
  await page.locator('#scan-button').click();
  await page.waitForFunction(() => document.querySelector('#count-skills').textContent === '4');
  assert.equal(await page.locator('.card').count(), 4);
  assert.equal(await page.locator('#count-sources').textContent(), '5');
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#download').click()]);
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
  assert.equal(exported.sections.flatMap(section => section.skills).length, 4);
  await page.locator('[data-category="product"]').click();
  assert.equal(await page.locator('.card').count(), 1);
  await page.locator('[data-category="all"]').click();
  await page.locator('#search').fill('.claude');
  assert.equal(await page.locator('.card').count(), 1);
  await page.locator('.card').click();
  await page.waitForFunction(() => document.querySelector('#manifest-content').textContent.includes('name: shared-skill'));
  assert.equal(await page.locator('#source-select option').count(), 2);
  await page.locator('#source-select').selectOption('.claude/skills/shared/SKILL.md');
  await page.waitForFunction(() => document.querySelector('#manifest-message').textContent === '');
  await page.locator('#close-detail').click();
  await page.locator('#search').fill('no-such-skill');
  assert.equal(await page.locator('.card').count(), 0);
  await page.getByText('No matching skills.', { exact: true }).waitFor();
  await page.locator('#search').fill('');
  await page.screenshot({ path: path.join(root, 'reports/web-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(root, 'reports/web-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile layout overflows');
  await page.locator('#repository-path').fill(path.join(root, 'does-not-exist'));
  await page.locator('#scan-button').click();
  await page.locator('#message.error').waitFor();
  assert.equal(await page.locator('.card').count(), 4, 'Failed scan should preserve old inventory');
  assert.deepEqual(errors, [], 'Browser console errors');
  console.log('Browser checks passed: scan, counters, filters, source search, detail, mirrors, empty state, mobile layout, error handling.');
} finally {
  clearTimeout(timeout);
  if (browser) await browser.close();
  server.kill();
  await once(server, 'exit');
}
